### ISSUE TITLE
GF(2) not work

### ISSUE THREAD

**Issue by cuihaoleo** [lrq3000/reedsolomon#2]
I need an GF(2) encoder like MATLAB's bchenc function.

Seems there is a bug in this lib when setting `c_exp=2` (I ran in python 3.6):

```
$ python -c "from reedsolo import RSCodec; rs = RSCodec(nsym=20, c_exp=2)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cuihao/.local/lib/python3.6/site-packages/reedsolo-1.4.0-py3.6-linux-x86_64.egg/reedsolo.py", line 861, in __init__
    self.gf_log, self.gf_exp, self.field_charac = init_tables(prim, generator, c_exp)
  File "/home/cuihao/.local/lib/python3.6/site-packages/reedsolo-1.4.0-py3.6-linux-x86_64.egg/reedsolo.py", line 293, in init_tables
    x = gf_mult_noLUT(x, generator, prim, field_charac+1)
  File "/home/cuihao/.local/lib/python3.6/site-packages/reedsolo-1.4.0-py3.6-linux-x86_64.egg/reedsolo.py", line 387, in gf_mult_noLUT
    if prim > 0 and x & field_charac_full: x = x ^ prim # GF modulo: if x >= 256 then apply modular reduction using the primitive polynomial (we just substract, but since the primitive number can be above 256 then we directly XOR).
TypeError: '>' not supported between instances of 'list' and 'int'
```

**Comment by cuihaoleo** [comment]
hmm, sorry. Think I need read my textbook to get a correct understanding about these parameters.
